CREATE UNIQUE PROPERTY INDEX ON forum        (id);
CREATE UNIQUE PROPERTY INDEX ON message      (id);
CREATE UNIQUE PROPERTY INDEX ON post         (id);
CREATE UNIQUE PROPERTY INDEX ON "Comment"    (id);
CREATE UNIQUE PROPERTY INDEX ON organization (id);
CREATE UNIQUE PROPERTY INDEX ON person       (id);
CREATE UNIQUE PROPERTY INDEX ON place        (id);
CREATE UNIQUE PROPERTY INDEX ON tag          (id);
CREATE UNIQUE PROPERTY INDEX ON tagclass     (id);
CREATE INDEX ON ldbc.person USING gin (properties JSONB_path_ops);
CREATE INDEX ON ldbc.tag    USING gin (properties JSONB_path_ops);
CREATE INDEX ON ldbc.place  USING gin (properties JSONB_path_ops);
CREATE PROPERTY INDEX ON message   ( creationDate DESC, id ASC );
CREATE PROPERTY INDEX ON post      ( creationDate DESC, id ASC );
CREATE PROPERTY INDEX ON "Comment" ( creationDate DESC, id ASC );
